# Generated by Django 5.2.11 on 2026-04-15 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='delivery_end_date',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='delivery_start_date',
        ),
        migrations.AddField(
            model_name='ordercart',
            name='delivery_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercart',
            name='delivery_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercart',
            name='frequency_months',
            field=models.PositiveIntegerField(choices=[(1, '1 Month'), (6, '6 Months'), (12, '1 Year'), (24, '2 Years')], default=1),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('order_confirmed', 'Order Confirmed'), ('payment_received', 'Payment Received'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='cart', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordercart',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('order_confirmed', 'Order Confirmed'), ('payment_received', 'Payment Received'), ('cancelled', 'Cancelled')], default='cart', max_length=20),
        ),
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('shipping_address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(default='Kerala', max_length=80)),
                ('pincode', models.CharField(max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shipping Details',
            },
        ),
    ]
