# Generated by Django 5.2.11 on 2026-04-16 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_delete_productfreq'),
        ('customer', '0002_remove_customerorder_delivery_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercart',
            name='frequency',
            field=models.ForeignKey(blank=True, help_text='Linked to admin_panel.Frequency', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.frequency'),
        ),
        migrations.AlterField(
            model_name='ordercart',
            name='frequency_months',
            field=models.PositiveIntegerField(default=1, help_text='Month count derived from Frequency label'),
        ),
    ]
