# Generated by Django 5.2.11 on 2026-04-20 04:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_product_image'),
        ('customer', '0003_ordercart_frequency_alter_ordercart_frequency_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='payment_type',
            field=models.CharField(choices=[('one_time', 'One-time'), ('monthly', 'Monthly')], default='one_time', max_length=10),
        ),
        migrations.AddField(
            model_name='ordercart',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivering', 'Delivering'), ('paused', 'Paused — Payment Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordercart',
            name='frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.frequency'),
        ),
        migrations.AlterField(
            model_name='ordercart',
            name='frequency_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='DailyDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('missed', 'Missed'), ('holiday', 'Customer Holiday')], default='delivered', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs_marked', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='customer.ordercart')),
            ],
            options={
                'ordering': ['-delivery_date'],
                'unique_together': {('order_item', 'delivery_date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(help_text='First day of the month this payment covers. E.g. 2026-04-01')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payments', to='customer.ordercart')),
            ],
            options={
                'ordering': ['month_year'],
                'unique_together': {('order_item', 'month_year')},
            },
        ),
    ]
