# Generated by Django 5.2.11 on 2026-04-26 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customerorder_payment_type_ordercart_delivery_status_and_more'),
        ('login', '0007_alter_agent_phone_alter_customer_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=50)),
                ('comp_date', models.DateField(auto_now_add=True)),
                ('comp_reply', models.CharField(default='', max_length=50)),
                ('comp_status', models.CharField(choices=[('Pending', 'Pending'), ('In Review', 'In Review'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='login.agent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
