# Generated by Django 5.2.11 on 2026-02-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('price_from', models.CharField(max_length=10)),
                ('mag_type', models.CharField(max_length=20)),
                ('issue_day', models.DateField()),
                ('details', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=15)),
                ('supplier_code', models.IntegerField()),
                ('supp_addr', models.CharField(max_length=50)),
                ('supp_phone', models.CharField(max_length=10)),
                ('supp_status', models.CharField(max_length=15)),
            ],
        ),
    ]
