# Generated by Django 5.2.11 on 2026-02-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_productfreq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfreq',
            old_name='frequency_id',
            new_name='frequency',
        ),
        migrations.RenameField(
            model_name='productfreq',
            old_name='product_id',
            new_name='product',
        ),
    ]
