# Generated by Django 5.2.11 on 2026-02-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_rename_frequency_id_productfreq_frequency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supp_addr',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_code',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='frequency',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mag_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supp_phone',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supp_status',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='frequency',
            name='frequency',
            field=models.CharField(default='Daily', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='management_type',
            field=models.CharField(default='testt', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='ddd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='ddfdff', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(default='sdfdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(default='123', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(default='Inactive', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_from',
            field=models.CharField(max_length=20),
        ),
    ]
