# Generated by Django 5.2.11 on 2026-03-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_rename_supp_addr_supplier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='product',
            field=models.ManyToManyField(blank=True, to='admin_panel.product'),
        ),
    ]
