# Generated by Django 5.2.11 on 2026-03-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_supplier_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='product',
            field=models.ManyToManyField(blank=True, db_table='admin_panel_supplier_product', to='admin_panel.product'),
        ),
    ]
