# Generated by Django 5.2.11 on 2026-03-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_supplier_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frequency',
            field=models.ManyToManyField(blank=True, to='admin_panel.frequency'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='product',
            field=models.ManyToManyField(blank=True, to='admin_panel.product'),
        ),
    ]
