# Generated by Django 5.2.11 on 2026-03-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_product_frequency_alter_supplier_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductFreq',
        ),
    ]
