# Generated by Django 5.2.11 on 2026-04-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='management_type',
            new_name='magazine_type',
        ),
    ]
