# Generated by Django 5.2.11 on 2026-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_rename_management_type_product_magazine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='issue_day',
            field=models.CharField(max_length=50),
        ),
    ]
