# Generated by Django 5.2.11 on 2026-04-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_alter_supplier_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='issue_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
