# Generated by Django 5.2.11 on 2026-04-26 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_alter_product_issue_day'),
        ('login', '0007_alter_agent_phone_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
                ('notification_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=15)),
                ('agent', models.ForeignKey(blank=True, help_text='Leave blank to send to all users', null=True, on_delete=django.db.models.deletion.CASCADE, to='login.agent')),
            ],
            options={
                'ordering': ['-notification_date'],
            },
        ),
    ]
