# Generated by Django 5.2.11 on 2026-02-17 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('code', models.IntegerField()),
                ('address', models.TextField(max_length=50)),
                ('phone', models.IntegerField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('forget_question', models.TextField(max_length=50)),
                ('forget_question_answer', models.TextField(max_length=50)),
                ('total_customers', models.IntegerField()),
                ('status', models.CharField(default='Inactive', max_length=10)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
