# Generated by Django 5.2.11 on 2026-03-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_rename_supp_addr_supplier_name_and_more'),
        ('login', '0003_alter_agent_login_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='location',
            field=models.ManyToManyField(null=True, to='admin_panel.location'),
        ),
    ]
