# Generated by Django 5.2.11 on 2026-04-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_agent_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='address',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(max_length=250),
        ),
    ]
