# Generated by Django 5.2.11 on 2026-03-07 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0005_supplier_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSupp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.CharField(default='Inactive', max_length=15)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.supplier')),
            ],
        ),
    ]
