# Generated by Django 5.2.11 on 2026-03-07 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_supplier_product'),
        ('agent', '0001_initial'),
        ('login', '0005_alter_agent_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsupp',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.agent'),
        ),
        migrations.AlterField(
            model_name='agentsupp',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.supplier'),
        ),
    ]
