# Generated by Django 5.2.11 on 2026-04-27 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_notification'),
        ('agent', '0002_agentsupp_agent_alter_agentsupp_supplier'),
        ('login', '0007_alter_agent_phone_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_place', models.CharField(max_length=20)),
                ('end_place', models.CharField(max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.agent')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_copies', models.IntegerField()),
                ('delivery_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='agent.deliveryround')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.product')),
            ],
        ),
    ]
